version: '3'

# 部署指南：
# 1.运行 Water 助理工具 完成初始化
#   > docker run -it --rm -p 19371:19371 noearorg/xwater:2.9.3
# 2.把配置里的 water.ds.* 换成真实的 WaterDb，并启动
# 3.管理后台地址 http://localhost:9373 做日常管理
# 4.使用 water-solon-cloud-plugin 时，配置为：solon.cloud.water.server=waterapi:9371

# 补充说明：最后的 gritadmin 服务是权限管理系统（water 内置了个简化版的。构用的话可删掉它）
# 1.权限管理地址 http://localhost:7281 做权限管理

services:
  waterapi:
    image: noearorg/waterapi:2.9.3
    container_name: waterapi
    environment:
      - water.ds.schema={water}
      - water.ds.server={water.mysql.io:3306} #提示：可以把 server 换成 url 属性，配置完整的 jdbcUrl
      - water.ds.username={demo}
      - water.ds.password={1234}
      - TZ=Asia/Shanghai
    ports:
      - 9371:9371
  watersev:
    image: noearorg/watersev:2.9.3
    container_name: watersev
    environment:
      - solon.start.ping=waterapi:9371
      - TZ=Asia/Shanghai
    depends_on:
      -  waterapi
    ports:
      - 9372:9372
  wateradmin:
    image: noearorg/wateradmin:2.9.3
    container_name: wateradmin
    environment:
      - solon.start.ping=waterapi:9371
      - TZ=Asia/Shanghai
    depends_on:
      -  waterapi
    ports:
      - 9373:9373
  waterfaas:
    image: noearorg/waterfaas:2.9.3
    container_name: waterfaas
    environment:
      - solon.start.ping=waterapi:9371
      - TZ=Asia/Shanghai
    depends_on:
      -  waterapi
    ports:
      - 9374:9374
